In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("IMDB Dataset.csv")

In [3]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [4]:
df.shape

(50000, 2)

In [5]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [6]:
df.drop_duplicates(inplace = True)

In [7]:
df.shape

(49582, 2)

### Pre Processing

In [8]:
df["review"] = df["review"].str.lower()

In [9]:
df["review"]

0        one of the other reviewers has mentioned that ...
1        a wonderful little production. <br /><br />the...
2        i thought this was a wonderful way to spend ti...
3        basically there's a family where a little boy ...
4        petter mattei's "love in the time of money" is...
                               ...
49995    i thought this movie did a down right good job...
49996    bad plot, bad dialogue, bad acting, idiotic di...
49997    i am a catholic taught in parochial elementary...
49998    i'm going to have to disagree with the previou...
49999    no one expects the star trek movies to be high...
Name: review, Length: 49582, dtype: object

### Removing URL

In [10]:
import re  # re - regular expression
#sample = "Trump is the boss, How di Trump"

#new = re.sub("Trump" , "Modi" , sample)  #(pattern , replacement , String)

In [11]:
#new

In [12]:
def remove_urls(text):
     text =  re.sub(r"http\S+" , "" , text) #(pattern , replacement , String) eg - https://www.google.com
     return text
    
df["review"] = df["review"].apply(remove_urls)

### Removing Puncutations

In [13]:
def remove_punctuations(text):
     text = re.sub(r"[^A-Za-z0-9\s]" , "" , text) # exculde [A-Z , a-z , 0-9 , white spaces \s] apart from this punctuations(include) - replace empty space
     return text

df["review"] = df["review"].apply(remove_punctuations)

In [14]:
df.head()

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production br br the filmin...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically theres a family where a little boy j...  negative
4  petter matteis love in the time of money is a ...  positive

### Removing HTML

In [15]:
def remove_html(text):
    text = re.sub(r"<.*?>" , "" , text) # ? - non-greedy manner remove , first closing tag -stop , remove HTML - space
    return text

df["review"] = df["review"].apply(remove_html)

### Removing Stopwords

In [16]:
#NLTK is the Python library, while punkt, punkt_tab, and stopwords are downloadable data resources that help the 
# nltk library perform specific NLP tasks.
import nltk # python library

nltk.download("punkt")   # Data used for sentence and word tokenization.
nltk.download("punkt_tab") # Additional tokenizer data required by certain NLTK versions
nltk.download("stopwords") # Lists of common words, such as the, is, an, and are, in different languages.

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\HP\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\HP\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\HP\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [17]:
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

# nltk - Pyhthon Library(collections of module)
# tokenize - Module inside the nltk library
#corpus - Module inside the nltk library
# word_tokenize - Indepedent function inside the tokenize module.

In [18]:
# sample = "I will become Job ready and Employable for AI and Data Sceince roles"

# tokens = word_tokenize(sample)
# stop_wd = stopwords.words("english")

# for word in tokens:
#    if word in stop_wd:
#        sample = sample.replace(word , "")

In [19]:
#sample

In [20]:
def remove_stopwd(text):
    tokens = word_tokenize(text)
    stop_word = stopwords.words("english")

    for word in tokens:
        if word in stop_word:
            text = text.replace(word , "")

    return text

df["review"] = df["review"].apply(remove_stopwd)

### Stemming

In [21]:
from nltk.stem import PorterStemmer

In [22]:
def stemming(text):
    ps = PorterStemmer()
    stem_word = []

    tokens = word_tokenize(text) # First tokenization perform
    for token in tokens:
        stem_token = ps.stem(token)  # convert each token into its root form
        stem_word.append(stem_token)  # empty list append new tokens

    return " ".join(stem_word)    # No return text(as return list , convert into text by " ".join)

df["review"] = df["review"].apply(stemming)

In [23]:
# sample = "I am playing greating match of all time in an amazing manner including tangling "
# sample1 = "I am coding in python while coded in java and codes in css"

# stemming(sample)
# # stemming(sample1)

In [24]:
df.head()

                                              review sentiment
0  e revew nted wtchg 1 oz epod ll hook y rght ex...  positive
1  wder ltle producti br br film techniqu unssum ...  positive
2  thought th wder wy spend tme o hot summer week...  positive
3  bsclli re fmli lttle boy jke thk re zomb close...  negative
4  petter mtte love time mey vulli stunng film wt...  positive

### Label Encoding

In [25]:
from sklearn.preprocessing import LabelEncoder

In [26]:
le = LabelEncoder()
df["sentiment"] = le.fit_transform(df["sentiment"])

In [27]:
y = df["sentiment"]

In [28]:
y

0        1
1        1
2        1
3        0
4        1
        ..
49995    1
49996    0
49997    0
49998    0
49999    0
Name: sentiment, Length: 49582, dtype: int64

### Vectorization

In [29]:
df.head()

                                              review  sentiment
0  e revew nted wtchg 1 oz epod ll hook y rght ex...          1
1  wder ltle producti br br film techniqu unssum ...          1
2  thought th wder wy spend tme o hot summer week...          1
3  bsclli re fmli lttle boy jke thk re zomb close...          0
4  petter mtte love time mey vulli stunng film wt...          1

In [30]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [31]:
tf = TfidfVectorizer(max_features = 5000)

X = tf.fit_transform(df["review"])

In [32]:
X # now we have the raw data after vectorization to feed to our RNN

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 4057169 stored elements and shape (49582, 5000)>

In [33]:
print(X)
# total rows(Review) - 49581
# Total column(Features , vocabulary) - 5000
# coords(0 , 3538) - (1st review , map 3538th features or column ) , having TF-IDF Value - 0.055154

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 4057169 stored elements and shape (49582, 5000)>
  Coords	Values
  (0, 3538)	0.05515484681268887
  (0, 2869)	0.09361182809242374
  (0, 4940)	0.11467310366614668
  (0, 3003)	0.47200539890110405
  (0, 1275)	0.1357698919196183
  (0, 2289)	0.049500237517476293
  (0, 1933)	0.0791260308382
  (0, 3550)	0.0963974330192639
  (0, 1362)	0.06162489377343992
  (0, 1963)	0.061560444992697486
  (0, 218)	0.08588920995304898
  (0, 1620)	0.0738170550485134
  (0, 4368)	0.041994187696759305
  (0, 4170)	0.17799685402440263
  (0, 3692)	0.033532198172897175
  (0, 4737)	0.26798942924092045
  (0, 3804)	0.04427609784380831
  (0, 4769)	0.05877405881441711
  (0, 1739)	0.037520883911174724
  (0, 4496)	0.07614066339174266
  (0, 3856)	0.17537900435282314
  (0, 1630)	0.06142445471882175
  (0, 1862)	0.07433134577032253
  (0, 3329)	0.06406818508428483
  (0, 3332)	0.0844754682576354
  :	:
  (49581, 4890)	0.10682334916138103
  (49581, 1542)	0.17584072573791829
  (49581, 4493)	0.09410069396961679
  (49581, 433)	0.11251655954741112
  (49581, 4276)	0.10905956327445408
  (49581, 1958)	0.0999074542943991
  (49581, 554)	0.08424218838425554
  (49581, 2187)	0.14180348667063264
  (49581, 2217)	0.09535602544797335
  (49581, 4346)	0.17508214877875983
  (49581, 4629)	0.1157123083349983
  (49581, 3646)	0.087334023293812
  (49581, 4734)	0.12354122837064464
  (49581, 1977)	0.1279546327938257
  (49581, 526)	0.1247934452922504
  (49581, 2622)	0.17341357547872566
  (49581, 4457)	0.16002233459530202
  (49581, 2174)	0.18983797727912208
  (49581, 4032)	0.20100044911463438
  (49581, 341)	0.14784964476913964
  (49581, 2696)	0.1740080872946952
  (49581, 438)	0.13323526536564564
  (49581, 4980)	0.15095820717373318
  (49581, 1764)	0.15815315432712562
  (49581, 3489)	0.1519741559925848

In [61]:
feature_names = tf.get_feature_names_out()
print(feature_names[4890])
print(feature_names[3489])

worst
rentl

### Tensor Datasets and Data Loader

In [34]:
from sklearn.model_selection import train_test_split

X_train , X_test , y_train , y_test = train_test_split(

    X , y , test_size = 0.2  , random_state = 42
)

In [35]:
X_train.shape

(39665, 5000)

In [36]:
import os
os.environ["KMP_DUPLICATE_LIB_OK"] = "TRUE"

In [37]:
import torch
#import torch.nn as nn
from torch.utils.data import TensorDataset , DataLoader

In [53]:
print(type(X_train))
print(type(X_test))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

In [52]:
X_train = X_train.toarray() 
X_test = X_test.toarray()

In [40]:
# # if X_train - (sparse matrix which we not feed to Tensor dataset , covert to numpy array )
# x_train = X_train.toarray() convert spase matrix to numpyarray

# X_train_tensor = torch.tensor(X_train , dtype = torch.float32)
# X_test_tesnor = torch.tensor(X_test , dtype = torch.float32)
# y_train_tesnor = torch.tensor(y_train , dtype = torch.long)
# y_test_tensor = torch.tensor(y_test , dtype = torch.long)

# # loss fnx for classification cross entropy , that except traget value as long

In [54]:
 # Tensor Dataset - To define Dataset, access from Memory(RAM)
train_set = TensorDataset(

    torch.from_numpy(X_train).float(),  # Directly numpy array to tensor convert
    torch.from_numpy(y_train.values).float()
)

test_set = TensorDataset(

    torch.from_numpy(X_test).float(),
    torch.from_numpy(y_test.values).float()
)

In [55]:
# Data Loader - To define how the data will be loaded for traning

train_loader = DataLoader(train_set , shuffle = True , batch_size = 64 ) 
test_loader = DataLoader(test_set , shuffle = True , batch_size = 64)

### Build our RNN

In [56]:
import torch.nn as nn
import torch.optim as optim

In [69]:
# Many to one RNN Architecture(Sentiment Analysis)
class RNN(nn.Module):
    def __init__(self , input_size , hidden_size = 128 , num_layer =1):
        super().__init__()

        self.hidden_size = hidden_size  # Attribute create for class RNN
        self.num_layer = num_layer

        #RNN layer (Pytorch RNN already define)
        self.rnn = nn.RNN(input_size , hidden_size , num_layer , batch_first = True)

        # fully connected layer
        self.fc = nn.Linear(hidden_size ,1) # single output

    def forward(self , x):
        # optional - shape(num_layer , batch_size , hidden_size)
        h0 = torch.zeros(self.num_layer , x.size(0), self.hidden_size)

        out , _ = self.rnn(x , h0)
        # 1st value = hidden state of all the timesteps => (batch, seq_len, hidden size)
        # 2nd value = final hidden state of last timestep

        out = self.fc(out[:, -1, :])
        return out

In [74]:
input_size = X_train.shape[1]

model = RNN(input_size)  # object create , constructor call

criterion = nn.BCELoss() # Binary cross entropy loss for Binary classification
optimizer = optim.Adam(model.parameters())

In [75]:
 X_train.shape[1]

5000

### Traning and Evaluation

In [77]:
epochs = 10

for epoch in range(epochs):
    model.train()
    running_loss = 0.0

    for Xb , yb in train_loader:

        optimizer.zero_grad()  # for each batch fresh gradient compute, dont accumualte value of graident of previous batch

        Xb = Xb.unsqueeze(1)  # add singleton direction - 2D - 3D as model expect 3D value - for that we used unsqueeze function

        output = model(Xb)  # output dimension - (batch_size ,1) 2D  Forward propagation
        # but here output is not a probaility value
        output = torch.sigmoid(output.squeeze())  # (batch_size, ) sequeeze dimension , convert o/p value - probaility

        loss = criterion(output , yb)  # Loss compute
        loss.backward() # Bckward propagation - gradient compute
        optimizer.step() # weights update

        running_loss += loss # Total running loss cal for all batches(620) in 1 epoch
        
    train_loss = running_loss/len(train_loader)  # Avg loss per batch for 1 epoch
        
    print(f"epoch = {epoch}/{epochs} , loss = {train_loss}")

epoch = 0/10 , loss = 0.37594836950302124
epoch = 1/10 , loss = 0.2642139494419098
epoch = 2/10 , loss = 0.2487311065196991
epoch = 3/10 , loss = 0.24150454998016357
epoch = 4/10 , loss = 0.23739054799079895
epoch = 5/10 , loss = 0.23394669592380524
epoch = 6/10 , loss = 0.23186640441417694
epoch = 7/10 , loss = 0.23009037971496582
epoch = 8/10 , loss = 0.22854138910770416
epoch = 9/10 , loss = 0.22769826650619507

In [ ]:
# Loss minimum for that loss we get the best params - store model

In [63]:
X_train.shape

(39665, 5000)

In [64]:
len(train_loader)  # 39665/64 - 620 batches

620

In [81]:
model

RNN(
  (rnn): RNN(5000, 128, batch_first=True)
  (fc): Linear(in_features=128, out_features=1, bias=True)
)

In [78]:
print(model)

RNN(
  (rnn): RNN(5000, 128, batch_first=True)
  (fc): Linear(in_features=128, out_features=1, bias=True)
)

In [82]:
#print(list(model.parameters())) # best weight & bias value

# Evaluate Model

In [91]:
model.eval()

total =0
correct =0

with torch.no_grad():  # No gradiet compute(No BP) as we are doing testing not traning
    for Xb , yb in test_loader:
        

        Xb = Xb.unsqueeze(1)  # add singleton direction - 2D - 3D as model expect 3D value - for that we used unsqueeze function
        output = model(Xb) # FP but here again it is not probalility  - (batch_size , 1)

        predicted = (torch.sigmoid(output.squeeze()) > 0.5).float() # (batch_size, ) sequeeze dimension , convert o/p value - probaility

        total += yb.size(0)  # Total y_test - 9917

        correct += (predicted == yb).sum().item()  # sum store for all batches

In [93]:
print(correct)

8508

In [96]:
print(correct / total*100)  # cal Accuracy

85.79207421599274

In [99]:
print(correct/9917*100 )

85.79207421599274

In [85]:
print(yb)

tensor([0., 0., 1., 0., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 0., 1., 0., 0.,
        1., 0., 1., 1., 0., 0., 1., 0., 0., 0., 1., 0., 1., 0., 0., 1., 1., 1.,
        0., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0.])

In [86]:
y_test.shape

(9917,)

In [87]:
y_train.shape

(39665,)

In [89]:
yb.size(0)

49

In [100]:
len(y_test)

9917

In [101]:
len(test_loader)

155